@startuml

"Producteur : Structure(s) d'imagerie" -> "Consommateur : Plateforme téléradiologie" : Flux 2.1 **AnnulationDemandeIMG** \n <color #FireBrick>HTTP DELETE</color>
"Producteur : Structure(s) d'imagerie" <-- "Consommateur : Plateforme téléradiologie" : Flux 2.2 **Resultat AnnulationDemandeIMG**\n <color #FireBrick>200 OK</color>
@enduml