@startuml

"Producteur : Plateforme téléradiologie" -> "Consommateur : Structure(s) d'imagerie" : Flux 3.1 **AnnulationDemandeIMG** \n <color #FireBrick>HTTP DELETE</color>
"Producteur : Plateforme téléradiologie" <-- "Consommateur : Structure(s) d'imagerie" : Flux 3.2 **Resultat AnnulationDemandeIMG**\n <color #FireBrick>200 OK</color>
@enduml