@startuml

"Producteur : Structure(s) d'imagerie" -> "Consommateur : Plateforme téléradiologie" : Flux 1.1 **RéponseDemandeIMG** \n <color #FireBrick>HTTP POST</color>
"Producteur : Structure(s) d'imagerie" <-- "Consommateur : Plateforme téléradiologie" : Flux 1.2 **Resultat RéponseDemandeIMG**\n <color #FireBrick>201 Created</color>
@enduml